# Generated by Django 5.0 on 2024-01-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категорія')),
                ('link_to_product', models.URLField(max_length=255, verbose_name='Лінк на продукт')),
                ('update_date', models.DateTimeField(verbose_name='Дата оновлення даних')),
            ],
        ),
    ]
